version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # You might want to change this for production
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: '1234' # Ensure this is quoted if it contains special characters
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: fastapi_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount current directory to /app in container
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:1234@db:3306/test

  reflex_ui:
    build: .
    container_name: reflex_ui_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: reflex run --frontend-host 0.0.0.0 --backend-host 0.0.0.0 --frontend-port 3000 --backend-port 8001
    depends_on:
      - api

volumes:
  mysql_data:
